id,name,raw,category,processed,solution,target,version,targetnew,label
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,environment,relevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,machine,relevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,machine,relevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,machine,relevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,machine,relevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,machine,relevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,component,relevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,machine,relevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,environment,relevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,environment,relevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5971,80,"2023-05-17 11:03:46,017 | Failed at Play [16_nvme_vhba_device_ops_spec13] ************
2023-05-17 11:03:46,017 | TASK [16_nvme_vhba_device_ops_spec13][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number nvme v hba device ops spec number timestamp task number nvme v hba device ops spec number guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5975,80,"2023-05-16 16:25:30,016 | Failed at Play [19_e1000e_network_device_ops] **************
2023-05-16 16:25:30,016 | TASK [19_e1000e_network_device_ops][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number network device ops timestamp task number network device ops guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5965,80,"2023-05-16 18:26:29,016 | Failed at Play [26_wintools_uninstall_verify] **************
2023-05-16 18:26:29,016 | TASK [26_wintools_uninstall_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools un install verify timestamp task number win tools un install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,component,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,infrastructure,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,user,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,test,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,machine,irrelevant
5967,80,"2023-05-18 00:41:46,018 | Failed at Play [1_cpu_hot_add_basic] ***********************
2023-05-18 00:41:46,018 | TASK [1_cpu_hot_add_basic][Set VM CPU number and/or cores per socket number] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Server_ISO/ansible-vsphere-gos-validation/common/vm_set_cpu_number.yml:9
fatal: [localhost]: FAILED! => The available Memory resources in the parent resource pool are insufficient for the operation.
error message:
The available Memory resources in the parent resource pool are insufficient for the operation.",,timestamp failed at play number cpu hot add basic timestamp task number cpu hot add basic set vm cpu number and or cores per socket number task path home worker workspace ansible cycle ubuntu number server iso ansible vsphere gos validation common vm set cpu number yml number fatal localhost failed the available memory resources in the parent resource pool are insufficient for the operation error message the available memory resources in the parent resource pool are insufficient for the operation,retry,nimbus,202305221222,product,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,environment,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,component,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,infrastructure,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,user,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,test,irrelevant
5969,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 23.04] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.186.197.255]: FAILED! => Failed to update apt cache: unknown reason
error message:
Failed to update apt cache: unknown reason",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed failed to update apt cache unknown reason error message failed to update apt cache unknown reason,retry,targetvm,202305221222,product,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5962,80,"2023-05-16 13:44:52,016 | Failed at Play [11_stat_hosttime] **************************
2023-05-16 13:44:52,016 | TASK [11_stat_hosttime][Guest OS connection failure] *******
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number stat host time timestamp task number stat host time guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5963,80,"2023-05-16 11:41:39,016 | Failed at Play [06_check_ip_address] ***********************
2023-05-16 11:41:39,016 | TASK [06_check_ip_address][Guest OS connection failure] ****
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number check ip address timestamp task number check ip address guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,environment,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,component,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,infrastructure,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,user,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,test,irrelevant
5964,80,"2023-05-16 07:58:04,016 | Failed at Play [24_paravirtual_vhba_device_ops] ************
2023-05-16 07:58:04,016 | TASK [24_paravirtual_vhba_device_ops][Get the UUID of partition /dev/sdb1] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.04_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/create_disk_partition.yml:68
fatal: [localhost]: UNREACHABLE! => Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
error message:
Invalid/incorrect username/password. Skipping remaining 4 retries to prevent account lockout: Warning: Permanently added '10.78.188.115' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
root@10.78.188.115: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).",,timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops get the uuid of partition dev sdb number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities create disk partition yml number fatal localhost un reachable invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password error message invalid incorrect username password skipping remaining number retries to prevent account lockout warning permanently added ip address to the list of known hosts permission denied please try again permission denied please try again root ip address permission denied public key gss api key ex gss api with mic password,retry,targetvm,202305221222,product,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,environment,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,component,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,infrastructure,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,user,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,test,irrelevant
5966,80,"2023-05-11 12:38:53,011 | Failed at Play [19_pvrdma_network_device_ops] **************
2023-05-11 12:38:53,011 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] 
task path: /home/worker/workspace/Ansible_SLES_15SP4_70U1_LSILOGICSAS_VMXNET3_BIOS/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161
fatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'
error message:
Failed to run RDMA ping from client VM 'test_vm_client_20230511123328' to server VM 'test_vm'. Hit error 'cma event RDMA_CM_EVENT_REJECTED, error 8
wait for CONNECTED state 4'",,timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible sles lsi logic sas vmxnet number bios ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error cma event remote direct memory access cm event rejected error number wait for connected state number,retry,targetvm,202305221222,product,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,environment,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,component,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,infrastructure,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,user,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,test,irrelevant
5970,80,"2023-05-17 09:35:42,017 | Failed at Play [04_wintools_complete_install_verify] *******
2023-05-17 09:35:42,017 | TASK [04_wintools_complete_install_verify][Guest OS connection failure] 
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_32/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26
fatal: [localhost]: FAILED! => Guest winrm is not connectable in 300 seconds.
error message:
Guest winrm is not connectable in 300 seconds.",,timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify guest os connection failure task path home worker workspace ansible cycle windows number ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds,retry,targetvm,202305221222,product,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,environment,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,component,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,infrastructure,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,user,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,test,irrelevant
5974,80,"2023-05-18 05:47:53,018 | Failed at Play [23_gosc_cloudinit_staticip] ****************
2023-05-18 05:47:53,018 | TASK [23_gosc_cloudinit_staticip][Fetch file /tmp/cloud-init_2023-05-18-05-46-38.tar.gz from VM guest] 
task path: /home/worker/workspace/Ansible_AlmaLinux_8.x_MAIN_PARAVIRTUAL_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/vm_guest_file_operation.yml:91
exception in /vmware_guest_file_operation.py when fetch in /client.py when _safe_read
fatal: [localhost]: FAILED! => local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)
error message:
local file write exception : IncompleteRead(80088 bytes read, 3777 more expected)",,timestamp failed at play number go sc cloud init static ip timestamp task number go sc cloud init static ip fetch file tmp cloud init timestamp number tar gz from vm guest task path home worker workspace ansible alma linux number x main para virtual vmxnet number efi ansible vsphere gos validation common vm guest file operation yml number exception in vmware guest file operation python when fetch in client python when safe read fatal localhost failed local file write exception incomplete read number bytes read number more expected error message local file write exception incomplete read number bytes read number more expected,retry,targetvm,202305221222,product,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,environment,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,infrastructure,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,user,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,test,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,machine,irrelevant
5968,80,"2023-05-17 09:53:06,017 | Failed at Play [1_deploy_vm] *******************************
2023-05-17 09:53:06,017 | TASK [1_deploy_vm][Send keys to yanans_winsrv_25335_nvme] **
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/vm_guest_send_key.yml:13
exception in /vmware_guest_sendkey.py when send_key_to_vm in /SoapAdapter.py when InvokeMethod
fatal: [localhost]: FAILED! => Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
error message:
Failed to send key (vim.vm.UsbScanCodeSpec.KeyEvent) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   usbHidCode = 2621447,
   modifiers = (vim.vm.UsbScanCodeSpec.ModifierType) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      leftControl = false,
      leftShift = false,
      leftAlt = false,
      leftGui = false,
      rightControl = false,
      rightShift = false,
      rightAlt = false,
      rightGui = false
   }
} to virtual machine due to vim.fault.TaskInProgress
2023-05-17 09:54:37,017 | TASK [1_deploy_vm][Testing exit due to failure] ************
task path: /home/worker/workspace/Ansible_Windows_Server_LTSC_Physical_main_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e",,timestamp failed at play number deploy vm timestamp task number deploy vm send keys toy an ans win srv number nvme task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common vm guest send key yml number exception in vmware guest send key python when send key to vm in soap adapter python when invoke method fatal localhost failed failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress error message failed to send key vim vm usb scan code spec key event dynamic type un set dynamic property vmodl dynamic property usb hid code number modifiers vim vm usb scan code spec modifier type dynamic type un set dynamic property vmodl dynamic property left control false left shift false left alt false left gui false right control false right shift false right alt false right gui false to virtual machine due to vim fault task in progress timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c physical main lsi logic sas efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e,retry,testbed,202305221222,product,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,environment,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,component,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,infrastructure,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,user,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,test,irrelevant
5972,80,"2023-05-16 12:33:31,016 | Failed at Play [25_lsilogic_vhba_device_ops] ***************
2023-05-16 12:33:31,016 | TASK [25_lsilogic_vhba_device_ops][Install packages on Ubuntu 22.10] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_22.10_Desktop_ISO/ansible-vsphere-gos-validation/linux/utils/install_uninstall_package.yml:148
fatal: [localhost -> 10.192.194.25]: FAILED! => '/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
error message:
'/usr/bin/apt-get -y -o ""Dpkg::Options::=--force-confdef"" -o ""Dpkg::Options::=--force-confold""       install 'sg3-utils=1.46-1build1'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/libsgutils2-2_1.46-1build1_amd64.deb  Could not connect to kazooie.canonical.com:80 (91.189.91.39). - connect (111: Connection refused) Could not connect to banjo.canonical.com:80 (91.189.91.38). - connect (111: Connection refused) Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::18), connection timed out Could not connect to us.archive.ubuntu.com:80 (2001:67c:1562::15), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sg3-utils/sg3-utils_1.46-1build1_amd64.deb  Unable to connect to us.archive.ubuntu.com:http:
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?",,timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops install packages on ubuntu number task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation linux utilities install un install package yml number fatal localhost ip address failed user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing error message user bin apt get y o dpkg options force configuration def o dpkg options force configuration old install sg number utilities number build number failed e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities libraries gut i ls number build number amd number deb could not connect to kazoo ie canonical com number ip address connect number connection refused could not connect to banjo canonical com number ip address connect number connection refused could not connect to us archive ubuntu com number ip address connection timed out could not connect to us archive ubuntu com number ip address connection timed out e failed to fetch http archive ubuntu com ubuntu pool main s sg number utilities sg number utilities number build number amd number deb unable to connect to us archive ubuntu com http e unable to fetch some archives maybe run apt get update or try with fix missing,retry,targetvm,202305221222,product,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,component,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,infrastructure,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,user,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,test,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,machine,irrelevant
5976,80,"2023-05-18 01:08:55,018 | Failed at Play [3_gosc_cloudinit_dhcp] *********************
2023-05-18 01:08:55,018 | TASK [3_gosc_cloudinit_dhcp][Check VMware Tools is running and collects guest IPv4 address successfully] 
task path: /home/worker/workspace/Ansible_Cycle_Ubuntu_23.04_Desktop_ISO/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49
fatal: [localhost]: FAILED! => [""It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds."", ""VMware Tools running status is 'guestToolsRunning'."", ""VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'."", ""VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.""]
error message:
It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.
VMware Tools running status is 'guestToolsRunning'.
VM's IP address in guest info is 'fd01:1:2:2917:250:56ff:fe81:7c85'.
VM's all IP addresses in guest info are '['fd01:1:2:2917:250:56ff:fe81:7c85', 'fe80::250:56ff:fe81:7c85']'.",,timestamp failed at play number go sc cloud init dhcp timestamp task number go sc cloud init dhcp check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible cycle ubuntu number desktop iso ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address,retry,nimbus,202305221222,product,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,component,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,infrastructure,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,user,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,test,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,machine,irrelevant
5973,80,"2023-05-15 21:58:18,015 | Failed at Play [01_deploy_vm] ******************************
2023-05-15 21:58:18,015 | TASK [01_deploy_vm][Change VM power state failure] *********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/vm_set_power_state.yml:69
fatal: [localhost]: FAILED! => Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out 
error message:
Unknown error while connecting to vCenter or ESXi API at 10.185.100.190:443 : [Errno 110] Connection timed out
2023-05-15 21:59:36,015 | TASK [01_deploy_vm][Testing exit due to failure] ***********
task path: /home/worker/workspace/Ansible_Cycle_Debian_10.x_64bit/ansible-vsphere-gos-validation/common/test_rescue.yml:86
fatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3
error message:
Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_paravirtual_vmxnet3",,timestamp failed at play number deploy vm timestamp task number deploy vm change vm power state failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common vm set power state yml number fatal localhost failed unknown error while connecting to vcenter or esxi api at ip address error number connection timed out error message unknown error while connecting to vcenter or esxi api at ip address error number connection timed out timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible cycle debian number x number b it ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi para virtual vmxnet number,retry,nimbus,202305221222,product,irrelevant
